# Generated by Django 4.1.4 on 2022-12-13 23:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='*')),
                ('rich_body', ckeditor.fields.RichTextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('source', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-published'],
            },
        ),
    ]
