# Generated by Django 4.1.4 on 2022-12-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date ')),
                ('post_id', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
