# Generated by Django 4.1.4 on 2022-12-28 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_category_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=datetime.datetime(2022, 12, 28, 13, 12, 7, 174098, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
